POST http://localhost:3001/api/routines
Content-Type: application/json

{
    "name": "sample",
    "time": "12:00"
}

###
GET http://localhost:3001/api/routines

###
PUT http://localhost:3001/api/routines/60e635e40148d91d5462314c
Content-Type: application/json

{
    "status": "Updated"
}